services:
  postgres:
    image: postgres:latest
    container_name: se_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SEDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: se-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/keycloak-config.json:/opt/keycloak/data/import/keycloak-config.json
    command:
      - start-dev
      - --import-realm
    networks:
      - local-network

volumes:
  postgres_data:

networks:
  local-network:
    driver: bridge