# Server
server.servlet.context-path=/api

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/SEDB
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/srm-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# JWT Configuration
jwt.auth.converter.resource-id=srm-exchange-client
jwt.auth.converter.principal-attribute=principal_username